"""alter users employee_code nullable and drop revoked_tokens jti unique constraint

Revision ID: 104551d9fda5
Revises: i9j0k1l2m3n4
Create Date: 2026-09-15 15:11:22.402595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104551d9fda5'
down_revision: Union[str, Sequence[str], None] = 'i9j0k1l2m3n4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('revoked_tokens_token_jti_key'), 'revoked_tokens', type_='unique')
    op.alter_column('users', 'employee_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'employee_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('revoked_tokens_token_jti_key'), 'revoked_tokens', ['token_jti'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
